moengage/Flutter-SDK

core/CHANGELOG.md
core/android/build.gradle
core/android/gradle/wrapper/gradle-wrapper.properties
core/android/src/main/kotlin/com/moengage/flutter/Constants.kt
core/android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
core/android/src/main/kotlin/com/moengage/flutter/MoEInitializer.kt
core/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
core/lib/constants.dart
core/lib/moe_android_core.dart
core/lib/moe_push_service.dart
core/lib/moengage_flutter.dart
core/lib/push_token.dart
core/lib/utils.dart
example/android/app/build.gradle
example/android/app/src/main/java/com/moengage/sampleapp/CustomPushListener.java
example/android/app/src/main/java/com/moengage/sampleapp/SampleApplication.java
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/lib/main.dart
example/pubspec.lock
example/pubspec.yaml
inbox/CHANGELOG.md
inbox/android/build.gradle
inbox/android/gradle/wrapper/gradle-wrapper.properties
inbox/android/src/main/kotlin/com/moengage/flutter/inbox/MoEngageInboxPlugin.kt

Android:
* MOEN-8794: Flutter set method call handler to null when the engine is in detached state
* MOEN-9805: Update Flutter Inbox Plugin with SDK version v6
* MOEN-9804: Update Flutter Core Plugin with native SDK v11
Common:
* Added Push Token callback

MOEN-8794 MOEN-9805 MOEN-9804 version 11 upgrade

---

.gitignore
core/CHANGELOG.md
core/android/build.gradle
core/ios/Classes/MOFlutterInitializer.swift
core/ios/Classes/MOFlutterPluginInfo.swift
core/ios/moengage_flutter.podspec
core/pubspec.yaml
example/.gitignore
example/android/app/build.gradle
example/android/build.gradle
example/ios/Flutter/AppFrameworkInfo.plist
example/ios/Flutter/Flutter.podspec
example/ios/Podfile
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner/AppDelegate.swift
example/pubspec.lock
example/pubspec.yaml
inbox/android/build.gradle
inbox/android/src/main/kotlin/com/moengage/flutter/inbox/MoEngageInboxPlugin.kt
inbox/ios/moengage_inbox.podspec
inbox/pubspec.yaml

https://moengagetrial.atlassian.net/browse/MOEN-17191

Flutter 3 support

---

.gitignore
core/CHANGELOG.md
core/android/build.gradle
core/ios/Classes/MOFlutterInitializer.swift
core/ios/Classes/MOFlutterPluginInfo.swift
core/ios/moengage_flutter.podspec
core/pubspec.yaml
example/.gitignore
example/android/app/build.gradle
example/ios/Flutter/AppFrameworkInfo.plist
example/ios/Flutter/Flutter.podspec
example/ios/Podfile
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner/AppDelegate.swift
example/pubspec.lock
example/pubspec.yaml
inbox/android/build.gradle
inbox/android/src/main/kotlin/com/moengage/flutter/inbox/MoEngageInboxPlugin.kt
inbox/ios/moengage_inbox.podspec
inbox/pubspec.yaml

Reverts moengage/Flutter-SDK#38

Revert "Flutter 3 support"

---

core/CHANGELOG.md
core/android/build.gradle
core/android/src/main/kotlin/com/moengage/flutter/Constants.kt
core/android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
core/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
core/lib/constants.dart
core/lib/model/permission_result.dart
core/lib/model/permission_type.dart
core/lib/moe_android_core.dart
core/lib/moe_cache.dart
core/lib/moe_core_controller.dart
core/lib/moengage_flutter.dart
core/lib/utils.dart
example/android/app/build.gradle
example/android/app/src/main/AndroidManifest.xml
example/android/build.gradle
example/lib/main.dart
example/lib/utils.dart
example/pubspec.lock

Push Permission APIs

---

core/CHANGELOG.md
core/ios/Classes/MoEngageFlutterPluginInfo.swift
core/ios/Classes/MoEngageInitializer.swift

https://moengagetrial.atlassian.net/browse/MOEN-18765: Updated Initialization method with SDKState. Instead of passing bool for sdkState, now initialization method accepts parameter of type MoEngageSDKState

MOEN-18765-Core: Updated initialization method with sdkState

---

core/CHANGELOG.md
core/android/build.gradle
example/android/app/build.gradle
example/android/build.gradle
inbox/CHANGELOG.md
inbox/android/build.gradle

Support for Android Native Sdk 12.4.00

Moen 18427 version update

---

core/CHANGELOG.md
core/lib/constants.dart
core/lib/in_app_payload_mapper.dart
core/lib/internal/logger.dart
core/lib/logger.dart
core/lib/model/push/moe_push_service.dart
core/lib/moe_core_controller.dart
core/lib/moengage_flutter.dart
core/lib/push_payload_mapper.dart
core/lib/utils.dart
example/lib/main.dart
example/lib/utils.dart
example/pubspec.lock
geofence/CHANGELOG.md
geofence/lib/moe_geofence_constants.dart
geofence/lib/moe_ios_geofence.dart
geofence/pubspec.yaml
inbox/CHANGELOG.md
inbox/lib/constants.dart
inbox/lib/moe_ios_inbox.dart
inbox/lib/payload_transformer.dart
inbox/pubspec.yaml

https://moengagetrial.atlassian.net/browse/MOEN-20366
Data Security Improvement - Disable logging in release mode. Implemented a custom logger with disabling logging in release environment
[MOEN-20366]: https://moengagetrial.atlassian.net/browse/MOEN-20366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOEN-20366 : Data Security Improvement - Disable Logging in Release Build

---

core/CHANGELOG.md
core/android/build.gradle
core/lib/constants.dart
core/lib/moengage_flutter.dart
example/android/app/build.gradle
example/lib/main.dart
inbox/android/build.gradle

https://moengagetrial.atlassian.net/browse/MOEN-20823
DRM ID Support in Flutter

MOEN-20823 DRM Id Support In Flutter

---

core/CHANGELOG.md
core/android/build.gradle
example/lib/main.dart

https://moengagetrial.atlassian.net/browse/MOEN-23237
SelfHandled InApp Callback for Test Inapps and Event Triggered InApps

MOEN-23237 SelfHandled InApp callback for Test InApp and Event triggered InApps

---

core/CHANGELOG.md
core/ios/moengage_flutter.podspec
example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj
geofence/CHANGELOG.md
geofence/ios/moengage_geofence.podspec
inbox/CHANGELOG.md
inbox/ios/moengage_inbox.podspec

https://moengagetrial.atlassian.net/browse/MOEN-24257
Flutter SDK with iOS 9.8.0

MOEN-24257: Flutter SDK with iOS 9.8.0

---

cards/CHANGELOG.md
cards/android/build.gradle
cards/pubspec.yaml

Updated Pubpec.yaml and Changelog

Pubspec Updates

---

example/android/app/build.gradle
example/android/gradle/appLibs.versions.toml
example/android/settings.gradle

https://moengagetrial.atlassian.net/browse/MOEN-27544
Add Version Catalogue for SampleApp

MOEN-27544 Add Version catalogue For SampleApp

---

cards/moengage_cards_ios/CHANGELOG.md
cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
cards/moengage_cards_ios/pubspec.yaml
core/moengage_flutter_ios/CHANGELOG.md
core/moengage_flutter_ios/ios/Classes/MoEngageFlutterPluginInfo.swift
core/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
core/moengage_flutter_ios/pubspec.yaml
example/ios/Podfile.lock
geofence/moengage_geofence_ios/CHANGELOG.md
geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
geofence/moengage_geofence_ios/pubspec.yaml
inbox/moengage_inbox_ios/CHANGELOG.md
inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec
inbox/moengage_inbox_ios/pubspec.yaml

https://moengagetrial.atlassian.net/browse/MOEN-28448
iOS dependecy updates

iOS packages version updates

---

core/moengage_flutter_web/CHANGELOG.md
core/moengage_flutter_web/lib/moengage_flutter_web.dart
core/moengage_flutter_web/lib/utils.dart
example/lib/main.dart

https://moengagetrial.atlassian.net/browse/MOEN-28647

Feat(flutter-SDK): MOEN-28647 flutter web sdk

---

core/moengage_flutter/CHANGELOG.md
core/moengage_flutter/lib/src/moengage_flutter.dart
core/moengage_flutter/test/data_provider/data_provider.dart
core/moengage_flutter/test/mock_platform.dart
core/moengage_flutter/test/moengage_flutter_test.dart
core/moengage_flutter_platform_interface/CHANGELOG.md
core/moengage_flutter_platform_interface/test/data_provider/json_data.dart
core/moengage_flutter_platform_interface/test/parser_test.dart
core/moengage_flutter_web/CHANGELOG.md
core/moengage_flutter_web/lib/moengage_flutter_web.dart
core/moengage_flutter_web/lib/utils.dart
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart

https://moengagetrial.atlassian.net/browse/MOEN-28397
1. Support arrays of Strings, Ints, Doubles, and Numbers in flutter.
2. The array must contain non-optional items. Mixing above types with null will result in attribute not getting tracked.

MOEN-28397: Added support for array in user attributes

---

core/moengage_flutter/CHANGELOG.md
core/moengage_flutter/pubspec.yaml
core/moengage_flutter_web/CHANGELOG.md
core/moengage_flutter_web/lib/moengage_flutter_web.dart
core/moengage_flutter_web/pubspec.yaml

https://moengagetrial.atlassian.net/browse/SUP-18778

fix(webSDK-Flutter): SUP-18778 updated moengage object

---

core/moengage_flutter/CHANGELOG.md
core/moengage_flutter/pubspec.yaml
core/moengage_flutter_web/CHANGELOG.md
core/moengage_flutter_web/lib/moengage_flutter_web.dart
core/moengage_flutter_web/pubspec.yaml
example/web/index.html

Web SDK release

---

cards/moengage_cards_ios/CHANGELOG.md
cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
cards/moengage_cards_ios/pubspec.yaml
core/moengage_flutter_ios/CHANGELOG.md
core/moengage_flutter_ios/ios/Classes/MoEngageFlutterPluginInfo.swift
core/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
core/moengage_flutter_ios/pubspec.yaml
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
geofence/moengage_geofence_ios/CHANGELOG.md
geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
geofence/moengage_geofence_ios/pubspec.yaml
inbox/moengage_inbox_ios/CHANGELOG.md
inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec
inbox/moengage_inbox_ios/pubspec.yaml

https://moengagetrial.atlassian.net/browse/MOEN-29489
iOS packages version updates

MOEN-29489: iOS packages version updates

---

core/moengage_flutter/CHANGELOG.md
core/moengage_flutter_platform_interface/CHANGELOG.md
core/moengage_flutter_platform_interface/lib/src/internal/callback/callbacks.dart
core/moengage_flutter_platform_interface/lib/src/internal/moe_core_controller.dart
core/moengage_flutter_platform_interface/lib/src/utils/in_app_payload_mapper.dart
core/moengage_flutter_platform_interface/lib/src/utils/utils.dart

https://moengagetrial.atlassian.net/browse/MOEN-30429
Send Self-Handled InApp Callback when Data is Null

MOEN-30429 Send Self Handled InApp Callback when Data is Null

---

cards/moengage_cards_ios/CHANGELOG.md
cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
cards/moengage_cards_ios/pubspec.yaml
core/moengage_flutter_ios/CHANGELOG.md
core/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
core/moengage_flutter_ios/pubspec.yaml
example/ios/Runner.xcodeproj/project.pbxproj
geofence/moengage_geofence_ios/CHANGELOG.md
geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
geofence/moengage_geofence_ios/pubspec.yaml
inbox/moengage_inbox_ios/CHANGELOG.md
inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec
inbox/moengage_inbox_ios/pubspec.yaml

https://moengagetrial.atlassian.net/browse/MOEN-31365
Updated ios package to latest version

Updated ios package to latest version

---

cards/moengage_cards_ios/CHANGELOG.md
cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
cards/moengage_cards_ios/pubspec.yaml
core/moengage_flutter_ios/CHANGELOG.md
core/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
core/moengage_flutter_ios/pubspec.yaml
example/ios/Runner.xcodeproj/project.pbxproj
geofence/moengage_geofence_ios/CHANGELOG.md
geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
geofence/moengage_geofence_ios/pubspec.yaml
inbox/moengage_inbox_ios/CHANGELOG.md
inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec
inbox/moengage_inbox_ios/pubspec.yaml

MOEN-31365: Updated ios package to latest version (#118)

---

core/moengage_flutter/CHANGELOG.md
core/moengage_flutter_android/CHANGELOG.md
core/moengage_flutter_android/android/build.gradle
core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEInitializer.kt
inbox/moengage_inbox/CHANGELOG.md
inbox/moengage_inbox_android/CHANGELOG.md
inbox/moengage_inbox_android/android/src/main/kotlin/com/moengage/flutter/inbox/MoEngageInboxPlugin.kt

https://moengagetrial.atlassian.net/browse/MOEN-32307
ANR while accessing Plugin version from assets in Main Thread

MOEN-32307 ANR while accessing Plugin version from assets in Main Thread

---

example/ios/Runner/AppDelegate.swift
example/ios/Runner/Base.lproj/Main.storyboard

Updated sample app to simulate inapp touch issue

---

core/moengage_flutter/CHANGELOG.md
core/moengage_flutter/lib/src/moengage_flutter.dart
core/moengage_flutter_android/CHANGELOG.md
core/moengage_flutter_android/android/build.gradle
core/moengage_flutter_platform_interface/CHANGELOG.md
core/moengage_flutter_platform_interface/lib/src/model/properties.dart
core/moengage_flutter_platform_interface/lib/src/utils/utils.dart
core/moengage_flutter_platform_interface/test/data_provider/data_provider.dart
core/moengage_flutter_platform_interface/test/data_provider/json_data.dart
core/moengage_flutter_platform_interface/test/data_tracking_test.dart
core/moengage_flutter_platform_interface/test/parser_test.dart
core/moengage_flutter_web/CHANGELOG.md
core/moengage_flutter_web/README.md
core/moengage_flutter_web/lib/moengage_flutter_web.dart
core/moengage_flutter_web/lib/utils.dart
example/android/settings.gradle
example/lib/main.dart

https://moengagetrial.atlassian.net/browse/MOEN-31747
flutter platform core and web-specific changes for object support in user and event attributes

[MOEN-31747] flutter platform core and web-specific changes for object support in user and event attributes

---

cards/moengage_cards/CHANGELOG.md
cards/moengage_cards/pubspec.yaml
core/moengage_flutter/CHANGELOG.md
core/moengage_flutter/pubspec.yaml
geofence/moengage_geofence/CHANGELOG.md
geofence/moengage_geofence/pubspec.yaml
inbox/moengage_inbox/CHANGELOG.md
inbox/moengage_inbox/pubspec.yaml

https://moengagetrial.atlassian.net/browse/MOEN-33359
Exact Version Pinning for Dependencies

MOEN-33359 Exact Version Pinning for Dependencies

---

cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
core/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec

Pin iOS native dependancies to exact versions

MOEN-33220: Pin iOS native dependancies to exact versions

---

cards/moengage_cards/CHANGELOG.md
cards/moengage_cards_ios/CHANGELOG.md
cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
core/moengage_flutter/CHANGELOG.md
core/moengage_flutter_ios/CHANGELOG.md
core/moengage_flutter_ios/ios/Classes/MoEngageFlutterPluginInfo.swift
core/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
core/moengage_flutter_platform_interface/CHANGELOG.md
core/moengage_flutter_platform_interface/lib/moengage_flutter_platform_interface.dart
core/moengage_flutter_platform_interface/lib/src/internal/constants.dart
core/moengage_flutter_platform_interface/lib/src/model/analytics/analytics_config.dart
core/moengage_flutter_platform_interface/lib/src/model/moe_init_config.dart
core/moengage_flutter_platform_interface/lib/src/utils/init_config_payload_mapper.dart
core/moengage_flutter_platform_interface/test/data_provider/json_data.dart
example/.gitignore
example/lib/main.dart
geofence/moengage_geofence/CHANGELOG.md
geofence/moengage_geofence_ios/CHANGELOG.md
geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
inbox/moengage_inbox/CHANGELOG.md
inbox/moengage_inbox_ios/CHANGELOG.md
inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec

https://moengagetrial.atlassian.net/browse/MOEN-33220
Added boolean user attribute tracking customization in initialization API

MOEN-33220: Added boolean user attribute tracking customization in initialization API

---

core/moengage_flutter/pubspec.yaml
core/moengage_flutter_android/CHANGELOG.md
core/moengage_flutter_android/pubspec.yaml
core/moengage_flutter_ios/pubspec.yaml
core/moengage_flutter_web/CHANGELOG.md
core/moengage_flutter_web/pubspec.yaml

MOEN-33542: Version Update

---

core/moengage_flutter_ios/ios/Classes/MoEngageFlutterBridge.swift
core/moengage_flutter_ios/ios/Classes/MoEngageFlutterConstants.swift
core/moengage_flutter_ios/ios/Classes/MoEngageFlutterUtil.swift
core/moengage_flutter_platform_interface/lib/src/internal/constants.dart
example/lib/main.dart

https://moengagetrial.atlassian.net/browse/MOEN-32213
Multiple self handeled inapp iOS

MOEN-32213: Multiple self handeled inapp iOS

---

example/ios/Runner/AppDelegate.swift

https://moengagetrial.atlassian.net/browse/MOEN-34412
Add MoEngage methods to handle the push in sample app

MOEN-34412: Add MoEngage methods to handle the push in sample app

---

example/ios/Podfile
example/ios/PushTemplates/Info.plist
example/ios/Runner.xcodeproj/project.pbxproj

https://moengagetrial.atlassian.net/browse/MOEN-34482
Fixed rich notification issue in sample app

MOEN-34482: Fixed rich notification issue in sample app

---

cards/moengage_cards_ios/CHANGELOG.md
cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
core/moengage_flutter_ios/CHANGELOG.md
core/moengage_flutter_ios/ios/Classes/MoEngageFlutterBridge.swift
core/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/PushTemplates.xcscheme
geofence/moengage_geofence_ios/CHANGELOG.md
geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
inbox/moengage_inbox_ios/CHANGELOG.md
inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec

https://moengagetrial.atlassian.net/browse/MOEN-34390
Updated iOS dependency

MOEN-34390: Updated iOS dependency

---

README.md
example/android/settings.gradle
packages/moengage_cards/moengage_cards/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/android/build.gradle
packages/moengage_cards/moengage_cards_android/lib/moengage_cards_android.dart
packages/moengage_flutter/moengage_flutter/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/android/build.gradle
packages/moengage_flutter/moengage_flutter_android/lib/moengage_flutter_android.dart
packages/moengage_geofence/moengage_geofence/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_android/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_android/android/build.gradle
packages/moengage_geofence/moengage_geofence_android/lib/moengage_geofence_android.dart
packages/moengage_inbox/moengage_inbox/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_android/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_android/android/build.gradle

https://moengagetrial.atlassian.net/browse/MOEN-35491
Add `jsonEncode()` in missing APIs

MOEN-35491 Add `jsonEncode()` in missing APIs

---

.github/scripts/release.main.kts

https://moengagetrial.atlassian.net/browse/MOEN-35866
Workflow Script Update

MOEN-35866: Kotlin Script Update

---

example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj

https://moengagetrial.atlassian.net/browse/MOEN-37138

MOEN-37138: Xcode 16.2 update

---

example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
packages/moengage_cards/moengage_cards/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/android/build.gradle
packages/moengage_cards/moengage_cards_android/android/gradle/wrapper/gradle-wrapper.properties
packages/moengage_flutter/moengage_flutter/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/android/build.gradle
packages/moengage_flutter/moengage_flutter_android/android/gradle/wrapper/gradle-wrapper.properties
packages/moengage_geofence/moengage_geofence/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_android/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_android/android/build.gradle
packages/moengage_geofence/moengage_geofence_android/android/gradle/wrapper/gradle-wrapper.properties
packages/moengage_inbox/moengage_inbox/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_android/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_android/android/build.gradle
packages/moengage_inbox/moengage_inbox_android/android/gradle/wrapper/gradle-wrapper.properties

https://moengagetrial.atlassian.net/browse/MOEN-36211
AGP Version updated to 8.7.3

MOEN-36211: AGP Version update from `8.4.0` to `8.7.3`

---

example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
example/pubspec.yaml
packages/moengage_flutter/moengage_flutter_web/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_web/lib/constants.dart
packages/moengage_flutter/moengage_flutter_web/lib/moengage_flutter_web.dart
packages/moengage_flutter/moengage_flutter_web/lib/utils.dart

https://moengagetrial.atlassian.net/browse/MOEN-37110
Make availability of Multi-ID methods `identifyUser` and `getUserIdentities` in Flutter web

MOEN-37110 web sdk multi-id changes

---

packages/moengage_cards/moengage_cards/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/CHANGELOG.md
packages/moengage_cards/moengage_cards_ios/CHANGELOG.md
packages/moengage_flutter/moengage_flutter/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_ios/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_platform_interface/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_web/CHANGELOG.md
packages/moengage_geofence/moengage_geofence/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_android/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_ios/CHANGELOG.md
packages/moengage_inbox/moengage_inbox/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_android/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_ios/CHANGELOG.md

https://moengagetrial.atlassian.net/browse/MOEN-37103
- Release date updated from 24 Mar to 25 Mar

MOEN-37103: Release date update

---

packages/moengage_cards/moengage_cards_ios/CHANGELOG.md
packages/moengage_cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
packages/moengage_flutter/moengage_flutter_ios/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
packages/moengage_flutter/moengage_flutter_platform_interface/lib/src/model/inapp/display_rules.dart
packages/moengage_geofence/moengage_geofence_ios/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
packages/moengage_inbox/moengage_inbox_ios/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec

https://moengagetrial.atlassian.net/browse/MOEN-38393
Version upgrade for simplify inapp trigger

MOEN-38393: Version upgrade for simplify inapp trigger

---

example/lib/cards/cards_home.dart
example/lib/inapp.dart
packages/moengage_cards/moengage_cards/CHANGELOG.md
packages/moengage_cards/moengage_cards_platform_interface/CHANGELOG.md
packages/moengage_cards/moengage_cards_platform_interface/lib/src/internal/payload_mapper.dart
packages/moengage_cards/moengage_cards_platform_interface/lib/src/model/cards_data.dart
packages/moengage_cards/moengage_cards_platform_interface/lib/src/model/cards_info.dart
packages/moengage_cards/moengage_cards_platform_interface/lib/src/model/model.dart
packages/moengage_cards/moengage_cards_platform_interface/test/enum/static_image_type_test.dart
packages/moengage_cards/moengage_cards_platform_interface/test/models/cards_data_test.dart
packages/moengage_cards/moengage_cards_platform_interface/test/models/cards_info_test.dart
packages/moengage_flutter/moengage_flutter/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_platform_interface/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_platform_interface/lib/moengage_flutter_platform_interface.dart
packages/moengage_flutter/moengage_flutter_platform_interface/test/data_provider/data_provider.dart

https://moengagetrial.atlassian.net/browse/MOEN-39575
Export platforms class in `moengage_flutter_platform_interface`

MOEN-39575 Export Platforms class in `moengage_flutter_platform_interface`

---

example/android/settings.gradle
packages/moengage_cards/moengage_cards/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/android/build.gradle
packages/moengage_cards/moengage_cards_ios/CHANGELOG.md
packages/moengage_cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
packages/moengage_flutter/moengage_flutter/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/android/build.gradle
packages/moengage_flutter/moengage_flutter_ios/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
packages/moengage_geofence/moengage_geofence/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_ios/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
packages/moengage_inbox/moengage_inbox/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_ios/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec

https://moengagetrial.atlassian.net/browse/MOEN-39612
iOS native version updated

MOEN-39612: Native versions updated

---

packages/moengage_cards/moengage_cards/CHANGELOG.md
packages/moengage_cards/moengage_cards_ios/CHANGELOG.md
packages/moengage_cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
packages/moengage_flutter/moengage_flutter/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_ios/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
packages/moengage_geofence/moengage_geofence/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_ios/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
packages/moengage_inbox/moengage_inbox/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_ios/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec

https://moengagetrial.atlassian.net/browse/MOEN-40351
Updated iOS plugin base version

MOEN-40351: Updated iOS plugin base version

---

example/android/settings.gradle
packages/moengage_cards/moengage_cards/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/CHANGELOG.md
packages/moengage_cards/moengage_cards_android/android/build.gradle
packages/moengage_flutter/moengage_flutter/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_android/android/build.gradle
packages/moengage_geofence/moengage_geofence/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_android/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_android/android/build.gradle
packages/moengage_inbox/moengage_inbox/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_android/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_android/android/build.gradle

https://moengagetrial.atlassian.net/browse/MOEN-40472
Native SDK version upgrade

MOEN-40472 Native sdk version upgrade

---

packages/moengage_cards/moengage_cards/CHANGELOG.md
packages/moengage_cards/moengage_cards_ios/CHANGELOG.md
packages/moengage_cards/moengage_cards_ios/ios/moengage_cards_ios.podspec
packages/moengage_flutter/moengage_flutter/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_ios/CHANGELOG.md
packages/moengage_flutter/moengage_flutter_ios/ios/Classes/MoEngageFlutterPluginInfo.swift
packages/moengage_flutter/moengage_flutter_ios/ios/moengage_flutter_ios.podspec
packages/moengage_geofence/moengage_geofence/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_ios/CHANGELOG.md
packages/moengage_geofence/moengage_geofence_ios/ios/moengage_geofence_ios.podspec
packages/moengage_inbox/moengage_inbox/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_ios/CHANGELOG.md
packages/moengage_inbox/moengage_inbox_ios/ios/moengage_inbox_ios.podspec

https://moengagetrial.atlassian.net/browse/MOEN-40351
iOS native version update

MOEN-40351: iOS native version update
